[workspace]
members = [
    "bombastic/bombastic",
    "bombastic/api",
    "bombastic/indexer",
    "reservoir/reservoir",
    "reservoir/api",
    "exporter",
    "event-bus",
    "storage",
    "index",
]
